package exceptions;

public enum ErrorType {
	DATABASE_CONNECTION_FAILED,
	FAILED_TO_CLOSE_DB_CONNECTION,
	FAILED_TO_EXECUTE_QUERY,
	FAILED_TO_CREATE_COUPON,
	COMPANY_ALREADY_EXISTS,
	CUSTOMER_ALREADY_EXISTS,
	ENTITY_DOES_NOT_EXIST_IN_DB,
	ENTITY_RENAME_NOT_ALLOWED,
	COUPON_ALREADY_OWNED_BY_CUSTOMER,
	COUPON_ALREADY_EXPIRED,
	COUPON_AMOUNT_IS_ZERO,
	SCHEDULED_TASK_EXECUTION_FAILED,
	FAILED_TO_LOGIN,
	COUPON_DETAILS_ARE_INVALID
	
	
}
