package exceptions;
import javax.ws.rs.core.Response.Status;

public enum ErrorType {
	DATABASE_CONNECTION_FAILED(Status.INTERNAL_SERVER_ERROR),
	FAILED_TO_CLOSE_DB_CONNECTION(Status.INTERNAL_SERVER_ERROR),
	FAILED_TO_EXECUTE_QUERY(Status.INTERNAL_SERVER_ERROR),
	FAILED_TO_CREATE_COUPON(Status.INTERNAL_SERVER_ERROR),
	COMPANY_ALREADY_EXISTS(Status.INTERNAL_SERVER_ERROR),
	CUSTOMER_ALREADY_EXISTS(Status.INTERNAL_SERVER_ERROR),
	ENTITY_DOES_NOT_EXIST_IN_DB(Status.INTERNAL_SERVER_ERROR),
	ENTITY_RENAME_NOT_ALLOWED(Status.INTERNAL_SERVER_ERROR),
	COUPON_ALREADY_OWNED_BY_CUSTOMER(Status.INTERNAL_SERVER_ERROR),
	COUPON_ALREADY_EXPIRED(Status.INTERNAL_SERVER_ERROR),
	COUPON_AMOUNT_IS_ZERO(Status.INTERNAL_SERVER_ERROR),
	SCHEDULED_TASK_EXECUTION_FAILED(Status.INTERNAL_SERVER_ERROR),
	FAILED_TO_LOGIN(Status.UNAUTHORIZED),
	COUPON_DETAILS_ARE_INVALID(Status.INTERNAL_SERVER_ERROR);
	

private Status httpErrorCode;




ErrorType(Status httpErrorCode){
	this.httpErrorCode = httpErrorCode;
}
public Status getHttpErrorCode() {
	return httpErrorCode;
}


public void setHttpErrorCode(Status httpErrorCode) {
	this.httpErrorCode = httpErrorCode;
}

}